language: objective-c
before_install:
    - brew update
    - pod install
script: xctool -workspace Examples/VerificationExample/VerificationExample.xcworkspace -scheme VerificationExample test -sdk iphonesimulator
